### ISSUE TITLE
Does not seem to work with kohya's additional-networks extension

### ISSUE THREAD

**Issue by younyokel** [opparco/stable-diffusion-webui-composable-lora#5]
Hello. Just tried this extension, and it's awesome. Tried with built-in Lora, and it worked very well.

Here's a retro pin up Lora I trained on SD 2.1, generated on Illuminati Diffusion:
Composable Lora disabled:
<img src="https://user-images.githubusercontent.com/53343081/221602500-d6a156fd-bb3a-4571-8fad-3edc4e2f19d7.png" width="320" />

Composable Lora enabled:
<img src="https://user-images.githubusercontent.com/53343081/221602640-a76cd3cb-2594-4eff-bc6c-5f0c52cedb96.png" width="320" />

Some of my Loras [do not work using the built-in Lora](https://github.com/Linaqruf/kohya-trainer/issues/80#issuecomment-1427869840), so I use this extension by kohya:

https://github.com/kohya-ss/sd-webui-additional-networks

Using this, Composable Lora does not seem to work at all.

Composable Lora enabled:
<img src="https://user-images.githubusercontent.com/53343081/221603946-b308a89c-cecc-4fee-917d-8dd1daf14882.png" width="320" />

**Comment by cerarslan** [comment]
This is what I'm looking for.

**Comment by Season02** [comment]
just use mask of addition network
